version: '3'

services:
  spine-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=vYYMMDD.rX
        # YY - Year
        # MM - Month
        # DD - Day
        # rX - Revision
    container_name: spine-manager
    ports:
      - "5000:5000"
    volumes:
      - spine-data:/app/instance

volumes:
  spine-data:
    external: true