version: '3'
services:
  spine-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    container_name: spine-bookshelf-manager
    image: spine-bookshelf-manager:${VERSION}
    ports:
      - "5000:5000"
    volumes:
      - spine-data:/app/instance

volumes:
  spine-data:
    external: true