version: "3.9"

services:
  flask_app:
    container_name: spine-bookshelf
    image: spine-bookshelf-app:v2025.03.06.2
    build: .
    ports:
      - "5000:5000"
    volumes:
      - spine-data:/app/instance
